### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by GeAlSt** [deekue/macos_tiling_de#1]
When running  the install.sh script:

ln -svi -t "$HOME/.config" "$SRC/config/$I" 

returns 

ln: illegal option -- t
usage: ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file [target_file]
       ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file ... target_dir
       link source_file target_file

**Comment by deekue** [comment]
thanks for catching that.  even without the Linux flag, it was still wrong (－‸ლ)

fixed in [ef1b3a4](https://github.com/deekue/macos_tiling_de/commit/ef1b3a457519d80a2c10d56bda67a265b8a0734d)
